root: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:promise/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: .
  project: ./tsconfig.json
  sourceType: module
env:
  node: true
  es2022: true
  jest/globals: true
plugins:
  - import
  - simple-import-sort
  - promise
  - '@typescript-eslint'
  - jest
rules:
  '@typescript-eslint/await-thenable': error
  '@typescript-eslint/no-misused-promises':
    - error
    - checksVoidReturn: false
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  simple-import-sort/imports: error
  simple-import-sort/exports: error
overrides:
  - files:
      - src/*
    rules:
      import/no-default-export: off
      import/prefer-default-export: off
settings:
  jest:
    globalAliases:
      describe:
        - context
      fdescribe:
        - fcontext
      xdescribe:
        - xcontext
